/* :: auth module :: */

export const FINISH_SIGN_IN = 'FINISH_SIGN_IN'
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

/* :: playlists module :: */

export const FETCH_PLAYLISTS_BY_USER = 'FETCH_PLAYLISTS_BY_USER'
export const FETCH_PLAYLISTS_BY_USER_SUCCESS = 'FETCH_PLAYLISTS_BY_USER_SUCCESS'
export const FETCH_PLAYLISTS_BY_USER_FAILED = 'FETCH_PLAYLISTS_BY_USER_FAILED'

export const FETCH_PLAYLIST_BY_ID = 'FETCH_PLAYLIST_BY_ID'
export const FETCH_PLAYLIST_BY_ID_SUCCESS = 'FETCH_PLAYLIST_BY_ID_SUCCESS'
export const FETCH_PLAYLIST_BY_ID_FAILED = 'FETCH_PLAYLIST_BY_ID_FAILED'

/* :: tracks module :: */

export const FETCH_TRACKS_BY_PLAYLIST = 'FETCH_TRACKS_BY_PLAYLIST'
export const FETCH_TRACKS_BY_PLAYLIST_SUCCESS = 'FETCH_TRACKS_BY_PLAYLIST_SUCCESS'
export const FETCH_TRACKS_BY_PLAYLIST_FAILED = 'FETCH_TRACKS_BY_PLAYLIST_FAILED'

export const DELETE_TRACK_FROM_PLAYLIST_SUCCESS = 'DELETE_TRACK_FROM_PLAYLIST_SUCCESS'
